const actionTypes = {
    SORT_BY_PRICE: "SORT_BY_PRICE",
    OUT_OF_STOCK: "OUT_OF_STOCK",
    FILTER_CATEGORY: "FILTER_CATEGORY",
    LOW_TO_HIGH: "LOW_TO_HIGH",
    HIGH_TO_LOW: "HIGH_TO_LOW",
    PRICE: "PRICE",
    SHOES: "SHOES",
    ATHLEISURE: "ATHLEISURE",
    EQUIPMENTS: "EQUIPMENTS",
    ACCESSORIES: "ACCESSORIES",
    SET_RATING: "SET_RATING",
    CLEAR: "CLEAR",
    SET_RANGE: "SET_RANGE",
    SET_MIN: "SET_MIN",
    SET_MAX: "SET_MAX",
    LOGIN_USER: "LOGI_USER",
    LOGOUT_USER: "LOGOUT_USER",
    SET_CART: "SET_CART",
    SET_ERROR: "SET_ERROR",
    INITIALIZE: "INITIALIZE",
    SET_ADDRESS: "SET_ADDRESS",
}

export {
    actionTypes
};